"""add_trips_table

Revision ID: 7db8928812ce
Revises: c2313ad0a0ee
Create Date: 2025-09-14 22:54:25.767320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7db8928812ce'
down_revision: Union[str, Sequence[str], None] = 'c2313ad0a0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.drop_index(op.f('idx_locations_coords'), table_name='locations')
    op.add_column('trips', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('cancellation_reason', sa.String(length=500), nullable=True))
    op.add_column('trips', sa.Column('trip_type', sa.String(length=50), nullable=True))
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('idx_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('idx_trips_driver_status'), table_name='trips')
    op.drop_index(op.f('idx_trips_requested_at'), table_name='trips')
    op.drop_index(op.f('idx_trips_rider_id'), table_name='trips')
    op.drop_index(op.f('idx_trips_status'), table_name='trips')
    op.drop_index(op.f('idx_trips_status_requested'), table_name='trips')
    op.drop_column('trips', 'rejection_reason')
    op.drop_column('trips', 'rejected_at')
    op.drop_column('trips', 'actual_distance_km')
    op.drop_column('trips', 'actual_cost_tnd')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('actual_cost_tnd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('actual_distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('rejected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('rejection_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_trips_status_requested'), 'trips', ['status', 'requested_at'], unique=False)
    op.create_index(op.f('idx_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('idx_trips_rider_id'), 'trips', ['rider_id'], unique=False)
    op.create_index(op.f('idx_trips_requested_at'), 'trips', ['requested_at'], unique=False)
    op.create_index(op.f('idx_trips_driver_status'), 'trips', ['driver_id', 'status'], unique=False)
    op.create_index(op.f('idx_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('trips', 'trip_type')
    op.drop_column('trips', 'cancellation_reason')
    op.drop_column('trips', 'assigned_at')
    op.create_index(op.f('idx_locations_coords'), 'locations', ['latitude', 'longitude'], unique=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('locations', 'latitude',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
