"""add_driver_status_column

Revision ID: 9823e9e78685
Revises: a03aed67a167
Create Date: 2025-08-20 19:59:55.078769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9823e9e78685'
down_revision: Union[str, Sequence[str], None] = 'a03aed67a167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('driver_status', sa.VARCHAR(length=20), nullable=False, server_default='offline'))
    op.alter_column('drivers', 'id_card',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('drivers', 'driver_license',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drivers', 'driver_license',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('drivers', 'id_card',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('drivers', 'driver_status')
    # ### end Alembic commands ###
