"""create_locations_table

Revision ID: c2313ad0a0ee
Revises: 9823e9e78685
Create Date: 2025-08-20 20:59:25.906424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2313ad0a0ee'
down_revision: Union[str, Sequence[str], None] = '9823e9e78685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('latitude', sa.Float(precision=10), nullable=False),
    sa.Column('longitude', sa.Float(precision=10), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locations_coords', 'locations', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_locations_role', 'locations', ['role'], unique=False)
    op.create_index('idx_locations_user_id', 'locations', ['user_id'], unique=False)
    op.create_index('idx_locations_user_updated', 'locations', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locations_user_updated', table_name='locations')
    op.drop_index('idx_locations_user_id', table_name='locations')
    op.drop_index('idx_locations_role', table_name='locations')
    op.drop_index('idx_locations_coords', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
